

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=testuser
#spring.datasource.password=19811981
#spring.datasource.url=jdbc:mysql://192.168.21.225:3306/mytest

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: testuser
#    password: 19811981
#    url: jdbc:mysql://192.168.21.225:3306/mytest
#  security:
#    oauth2:
#      sso:
#        login-path: /login
#      client:
#        client-id: 233668646673605
#        client-secret: 33b17e044ee6a4fa383f46ec6e28ea1d
##        accessTokenUri: https://graph.facebook.com/oauth/access_token
##        userAuthorizationUri: https://www.facebook.com/dialog/oauth
##        tokenName: oauth_token
##        authenticationScheme: query
##        clientAuthenticationScheme: form
##        registration:
##          google:
##            clientId: 437552427673-k9pe15e903ddshqo38sfgk8bo7aja6ki.apps.googleusercontent.com
##            clientSecret: ei_kE3NjHeXTjGpaYT6TaN3f
#      resource:
#        user-info-uri: https://graph.facebook.com/me


#spring.security.oauth2.resource.userInfoUri=https://accounts.google.com/o/oauth2/v2/auth

#spring.security.oauth2.client.clientId =437552427673-k9pe15e903ddshqo38sfgk8bo7aja6ki.apps.googleusercontent.com
#spring.security.oauth2.client.clientSecret =ei_kE3NjHeXTjGpaYT6TaN3f
#spring.security.oauth2.client.accessTokenUri  =  https://www.googleapis.com/oauth2/v3/token
#spring.security.oauth2.client.userAuthorizationUri  =  https://accounts.google.com/o/oauth2/auth
#spring.security.oauth2.client.tokenName = oauth_token
#spring.security.oauth2.client.authenticationScheme = query
#spring.security.oauth2.client.clientAuthenticationScheme = form
#spring.security.oauth2.client.scope = profile email
##
#spring.security.oauth2.resource.userInfoUri  =  https://www.googleapis.com/userinfo/v2/me
#spring.security.oauth2.resource.preferTokenInfo = false





#spring.security.oauth2.client.registration.google.client-id=368238083842-3d4gc7p54rs6bponn0qhn4nmf6apf24a.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=2RM2QkEaf3A8-iCNqSfdG8wP

#spring.security.oauth2.client.registration.google.client-id=437552427673-k9pe15e903ddshqo38sfgk8bo7aja6ki.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=ei_kE3NjHeXTjGpaYT6TaN3f

#security:
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 368238083842-3d4gc7p54rs6bponn0qhn4nmf6apf24a.apps.googleusercontent.com
            client-secret: 2RM2QkEaf3A8-iCNqSfdG8wP
security:
  oauth2:
    client:
      clientId: 437552427673-k9pe15e903ddshqo38sfgk8bo7aja6ki.apps.googleusercontent.com
      clientSecret: ei_kE3NjHeXTjGpaYT6TaN3f
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me